-- THIS FILE IS NOT USED YET
DROP TABLE IF EXISTS note;

-- CREATE TABLE note (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   title TEXT NOT NULL,
--   url TEXT NOT NULL,
--   cmd TEXT NOT NULL,
--   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
-- );